### ISSUE TITLE
PortalFrame.navigateTo(path!) does not work for sub-menu items

### ISSUE THREAD

**Issue by mjuryeci** [BBj-Plugins/WebKit#175]
when calling this function, only root menu items are correctly navigated to. Sub-menus do not display.

### for example:
/customers ✅ - root item of main menu! object, customersMenu! object. portal is reloaded after navigating to this url
/customers/paid ❌ - sub item of customersMenu! object. portal does not load menu tiles after navigating to this url

**Comment by mjuryeci** [comment]
**thats precisely what i am doing, except there is no program set for these menu items.
so here is an example of what i have going on:**

---------------------------------------------------------------------

declare Menu menu!
declare MenuItem parentMenu!
declare MenuItem subMenu!

menu! = new Menu()

parentMenu! = menu!.addMenuItem(menu!.getRoot(),101,"Customers","List of Customers","users")
parentMenu!.setPath("/customers") **_<-- navigating HERE works_**

subMenu! = menu!.addMenuItem(item!, 1000, "Customer Report Programs", "Customer Details", "details")
subMenu!.setPath("/customers/programs") **_<-- navigating HERE shows an empty portal_**

reportProgramA! = menu!.addMenuItem(subMenu!, 1001, "report program", ""report program", "details")
reportProgramA!.setProgram("/.../program.bbj")
reportProgramA!.setStartType(0)

reportProgramB! = menu!.addMenuItem(subMenu!, 1002, "report program", ""report program", "details")
reportProgramB!.setProgram("/.../program.bbj")
reportProgramB!.setStartType(0)

**Comment by TimonGeisbauer** [comment]
Hmm your sample code looks right. 
I replicated something similar on my machine and it works fine.
Would it be possible to see your exact code or to make a debug Session ?
