### ISSUE TITLE
BUG: Forgot Password Page Opens If We Put #home at URL

### ISSUE THREAD

**Issue by saadnoor** [BBj-Plugins/WebKit#34]
http://localhost:8888/webapp/ProdinDemo#Home

if we put it instead of http://localhost:8888/webapp/ProdinDemo, forget password page opens. Which souldn't be the case.

**Comment by prodin-ian** [comment]
Yeah we currently use  the # to send a renew password token behind the url. Im thinking to start the tokenURL with another symbol to distinguuish from navigation

**Comment by saadnoor** [comment]
this issue currently fixed in master branch. Checked.
